- name: Execute Flyway migration
  hosts: migration
  tasks:
    - include_role:
        name: lrk.flyway
      vars:
        flyway_url: 'jdbc:mysql://{{ db_host }}:{{ db_port }}/{{ db_name }}'
        flyway_user: '{{ db_user }}'
        flyway_password: '{{ db_password }}'
        flyway_connect_retries: 10
        flyway_schemas:
            - '{{ db_name }}'
        flyway_locations: 'filesystem:{{ migrations_folder }}'

- name: Install Docker
  hosts: app
  tasks:
    - include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_users:
          - '{{ ansible_ssh_user }}'

    - name: Run app
      shell: 'docker start app || docker run --name app -d -p 8080:8080 moleksyuk/demo --spring.datasource.url=jdbc:mysql://{{ db_host }}:{{ db_port }}/{{ db_name }} --spring.datasource.username={{ db_user }} --spring.datasource.password={{ db_password }}'
